my:
  greeting: Hello world from confgi server
  list.values: One, Two, Three, Four
  
db:
  connection: {connectionString: 'from confgi server', username: 'www', password: 'qqq'}
  host: 192.168.0.14
  port: 6541
