my.greeting: Hello world
app:
  name: my app
  description: welcome to ${app.name}

db:
  connection: {connectionString: 'http:___', username: 'foo', password: 'pass'}
  host: 192.168.0.14
  port: 3401

management.endpoints.web.exposure.include: "*"
spring.profiles.active: test
